### ISSUE TITLE
0.1.32 badly packaged

### ISSUE THREAD

**Issue by swisstofu** [lgalfaso/angular-dynamic-locale#100]
Hello, 

Checking tag 0.1.32, I noticed that https://github.com/lgalfaso/angular-dynamic-locale/blob/0.1.32/dist/tmhDynamicLocale.js still shows up version 0.1.30, and new method `addLocalePatternValue` is missing.

Therefore the published version has the same issue.

Could you please check ? thanks

**Comment by lgalfaso** [comment]
Thanks, this should be fixed now.
