### ISSUE TITLE
Improve packaging moving minified files to /dist directory

### ISSUE THREAD

**Issue by evilaliv3** [lgalfaso/angular-dynamic-locale#101]
According to most ommon best practices in packaging js libraries the minified versions should be delivered inside the ```/dist``` directory that is the one that should include all the build version result of the library packaging.

**Comment by evilaliv3** [comment]
The same should probably apply to the ```.map``` file.

**Comment by lgalfaso** [comment]
And in what form is different to what is present in the current `dist` directory?

**Comment by evilaliv3** [comment]
right, probably for error you are shipping them also into the root directory.

**Comment by lgalfaso** [comment]
Having this file in two places hurts nobody.
