### ISSUE TITLE
set does not update the $locale.id

### ISSUE THREAD

**Issue by 01willtx** [lgalfaso/angular-dynamic-locale#103]
When changing locale from 'en' to 'fr' the $locale.id property is still set to to 'en'

`           var locale = _.find(locales, function (l){ return l.countryCode === countryCode});
            if (locale) {
                        tmhDynamicLocale.set(locale.id);
             } else {
                        console.log("localeId not found using countryCode: " + countryCode);
             }`

The numberFormat property has the current settings but not the id. Using version 1.2.28 / angular 1.2.26 (can't upgrade angular at this time)

**Comment by lgalfaso** [comment]
At http://lgalfaso.github.io/angular-dynamic-locale/ there is an example that looks at `$locale.id` (if you look at the source code, it reads `<p>Current locale id: {{$locale.id}}</p>`, would it be possible for you to create a plunker that shows this error?

**Comment by 01willtx** [comment]
Hello! Thanks for the quick response! Here's the plunkr: http://plnkr.co/edit/MSgsrDXg2CRid5c5ywZv?p=preview

**Comment by lgalfaso** [comment]
the `$locale` object is not updated synchronously. There are several mechanism to know when `tmhDynamicLocale` updates the locale, in this case, the simplest would be to use the fact that `tmhDynamicLocale.set` returns a promise that is fulfilled when the locale changes. With this in mind, here is an updated version that takes this into consideration http://plnkr.co/edit/EdzfoUYWiQExjebDPEQc?p=preview

**Comment by 01willtx** [comment]
Ah, great! Thank you!

**Comment by 01willtx** [comment]
One more question please. So, after calling the update, will other directives relying on $locale have reference to the "new" one? The use case, during app initialization, the db is checked for a country code setting then the locale will be updated if different than the current. There are multiple directives relying on the $locale.

**Comment by lgalfaso** [comment]
The `$locale` object and all its properties are updated in-place (whenever possible).
