### ISSUE TITLE
How do we define a default locale ?

### ISSUE THREAD

**Issue by sebastienvermeille** [lgalfaso/angular-dynamic-locale#104]
Hello,
Thank you for this great bundle it works pretty well :+1: 

I have just a small problem:
At the first launch of my webapp it tries to load a file in /vendors/locales/locale_.js <--- it miss {{ locale }} like 'en' for example.

Can we define a default locale so that it take {{ locale }} and if undefined -> 'en' ? Thank you for your help I am sure you already answered it hundred of times but I didn't found it anywhere... 

Cheers,
Seb

**Comment by lgalfaso** [comment]
Hi, `tmhDynamicLocaleProvider.defaultLocale('en');`

**Comment by sebastienvermeille** [comment]
Cool works like a charm thank you ! :+1:
