### ISSUE TITLE
Issue with special characters

### ISSUE THREAD

**Issue by MMastrofini** [lgalfaso/angular-dynamic-locale#105]
When I use characters like `&`, `à` or `è`, I see their corresponding code, e.g. `&amp;` for `&` or `&#224;` for `à`. My version is 0.1.32.

**Comment by lgalfaso** [comment]
Hi, would it be possible to understand what the specific issue is? Would it be possible to have a plunker that shows the issue?

**Comment by MMastrofini** [comment]
I followed the step by step procedure. The module is working correctly, provided I don't use special characters. When I use special characters, I see their corresponding code, e.g. &amp; rather than & or &#224; rather than à.

E.g. in my HTML I have `<p>{{"FooterA" | translate}}</p>`. In my localized json file I have `{"FooterA":"--- è ---"} `and the output in the HTML page is `--- &#232; ---`

app.js is just 

angular
  .module('LASTHorizon', [
    'ngRoute', 'ngCookies', 'ui.router', 'ngSanitize', 'pascalprecht.translate', 'tmh.dynamicLocale', 'LocalStorageModule'
  ]);

```
app.controller('IndexCtrl', ['$scope', 'LocaleService', function ($scope, LocaleService) {
    $scope.currentLocaleDisplayName = LocaleService.getLocaleDisplayName();
    $scope.localesDisplayNames = LocaleService.getLocalesDisplayNames();
    $scope.visible = $scope.localesDisplayNames &&
      $scope.localesDisplayNames.length > 1;
    $scope.changeLanguage = function (locale) {
      LocaleService.setLocaleByDisplayName(locale);
    };
  }]
);
```

**Comment by lgalfaso** [comment]
This project is tmh.dynamicLocale, are you looking
for pascalprecht.translate?

**Comment by MMastrofini** [comment]
I am very sorry, I initially thought the problem was somewhere else. Thanks.
