### ISSUE TITLE
translate-attr fails on object keys with '-' symbol

### ISSUE THREAD

**Issue by dliu120** [lgalfaso/angular-dynamic-locale#107]
<ANY translate-attr="{ data-text: 'TRANSLATED_TEXT' }"></ANY>

fails because of a parse error with the object key having a '-'

https://docs.angularjs.org/error/$parse/syntax?p0=-&p1=is%20unexpected,%20expecting%20%5B%7D%5D&p2=7&p3=%7B

**Comment by lgalfaso** [comment]
Hey, are you sure you open this issue on the right project?

**Comment by dliu120** [comment]
You are right -- sorry wrong project!
