### ISSUE TITLE
Module 'tmh.dynamicLocale' is not available! You either misspelled the module name or forgot to load it

### ISSUE THREAD

**Issue by weldelmongi** [lgalfaso/angular-dynamic-locale#110]
i have this issue with  only IE9 when the code is minified( in production) :
Module 'tmh.dynamicLocale' is not available! You either misspelled the module name or forgot to load it

 i use angularjs 1.5 ,my version of    "angular-dynamic-locale": "0.1.32"
can you help me please ?

**Comment by lgalfaso** [comment]
Hi, do you have a minimal setup that is able to reproduce this issue?
If you have it, would it be possible for you to create a plunker with the minified version and another with the unminified version?

If possible, also post the steps you are using to minify your code.

Without some extra information, it is not possible to know what is going on.

**Comment by weldelmongi** [comment]
thank you for your quick answer , it is hard to reproduce this issue outside production platform ,
anyway i have solved the problem by changing the order of js files when they are minified by grunt :)

**Comment by lgalfaso** [comment]
Based on the previous comment, this might not be an issue with this library. Closing.
