### ISSUE TITLE
Ionic build android

### ISSUE THREAD

**Issue by andrewheyer** [lgalfaso/angular-dynamic-locale#111]
When using this in the browser with `ionic serve` I have no issue. I have a controller shown just like in the example, and I can switch back and forth between the locales I included in my index.html. However when I use ionic build it is giving me this error. 

<img width="835" alt="screen shot 2017-02-10 at 5 45 45 pm" src="https://cloud.githubusercontent.com/assets/19435085/22849270/d55f84f6-efb8-11e6-9b08-e15db023b305.png">

I used bower to install my packages, so I am sourcing both "angular-dynamic-local" and "angular-i18n" which are sourced from index.html. I also changed the default directory for angular-dynamic-local to find inside of the /lib folder. 

I find it strange that using `ionic serve` works fine, to me is merits enough that everything is configured correctly, but when I build and test on an android device it will not.

**Comment by lgalfaso** [comment]
I am not familiar with ionic, so I am not sure if I can help you here, but
have you tried
https://github.com/lgalfaso/angular-dynamic-locale/issues/93#issuecomment-210826808

?

**Comment by andrewheyer** [comment]
That fixed it! Inspecting the device with google chrome dev tools shows the file, thus I am now able to use with my ionic app. Thank you!!!!
