### ISSUE TITLE
when refresh the page default language displaying in dropdown

### ISSUE THREAD

**Issue by ajayreddy56** [lgalfaso/angular-dynamic-locale#112]
hi,

when i select the language from drop down it's working fine and when i refresh the web page the default language is holding in drop down.how to set, whatever language user selects and refreshes the web page  it should be same.

**Comment by lgalfaso** [comment]
The readme file at the main page reads

It is possible to specify a storage location for the locale using
tmhDynamicLocaleProvider.useStorage(storageName), the name of the storage
must follow the same signature as $cookieStore. The default storage
location is to use a $cache, this default storage is not persistent.

It is possible to ask the storage to be $cookieStore using the shortcut
tmhDynamicLocaleProvider.useCookieStorage(), internally this is exactly as
performing tmhDynamicLocaleProvider.useStorage('$cookieStore')


Is there anything in this issue that is not covered there?

**Comment by lgalfaso** [comment]
Without an update in quite some time, I think it is safe to close this issue.
