### ISSUE TITLE
@type definition

### ISSUE THREAD

**Issue by gerardolima** [lgalfaso/angular-dynamic-locale#113]
Hi, @lgalfaso, is there any Typescript definition file for tmhDynamicLocale?

**Comment by lgalfaso** [comment]
There is no Typescript definition, but a PR is welcome.

**Comment by gerardolima** [comment]
nice, I'm really short on time for this sprint, but I can do it soon

**Comment by tYYGH** [comment]
Hi! I see that the pull request has been merged (thanks! by the way).
Would it be possible to release a version, so that this feature can be made available through a `package.json` file?

**Comment by lgalfaso** [comment]
@tYYGH Had a slightly messy release cut as the automated script had some failures, but a new release is now live with the type information in `package.json`. Let me know if you have any issues.

**Comment by lgalfaso** [comment]
From the last comment, my understanding is that this issue is now solved.
