### ISSUE TITLE
Karma failure due to 'Possibly Unhandled Rejection'

### ISSUE THREAD

**Issue by Deklin** [lgalfaso/angular-dynamic-locale#117]
So if karma can't load the required file, we are getting an error

	the string "Possibly unhandled rejection: en-us" was thrown, throw an Error :)

Is there a way to define the rejection handler in the config phase for the dynamic locale?

**Comment by lgalfaso** [comment]
Would it be possible to know what are you specifically looking for?

When there is an error with the locale loading, there is a broadcast of
type $localeChangeError would this be enough for the issue you are facing?

**Comment by Deklin** [comment]
We are trying to figure out how to get by this.

What would be helpful is in the config phase to set a rejection method so we can log or toss the rejection. Because its unhandled when we do our unit tests right now, this is failing because of the unhandled rejection

something like;

  tmhDynamicLocaleProvider.onLocaleLoadFailure(function(e) {
// Toss the error.
};

I'm assuming somewhere there is a promise that is rejecting based on not loading the requested locale file, if we can swallow that or at least have a way to process it, that should solve it.

**Comment by Deklin** [comment]
I am also reviewing the code now to see if I can explain better or find the actual problem.

**Comment by lgalfaso** [comment]
tmhDynamicLocale.set returns a promise that is rejected when loading the
locale fails.

**Comment by lgalfaso** [comment]
From the last comment, my understanding is that this issue is resolved.

**Comment by rgeraldporter** [comment]
In case anyone else in the future needs a code example of the solution here, when setting the local, define a catch with an empty function:

```js
tmhDynamicLocale.set('en-US').catch(() => {});
```
