### ISSUE TITLE
Explicit annotation issue

### ISSUE THREAD

**Issue by JackPapa0156** [lgalfaso/angular-dynamic-locale#119]
When boostraping angular v5 app using **angular/upgrade module** I've found following issue:

> **function(tmhDynamicLocaleProvider)** is not using explicit annotation and cannot be invoked in strict mode.

After turning "strict-di" mode off everything is working:
`this.upgrade.bootstrap(document.body, ['my-app'], { strictDi: false });`

It seems that it is not possible to work in "strict-di" mode with included angular-dynamic-locale.

**Comment by lgalfaso** [comment]
Hi, any chance that it is your app that is trying to inject
tmhDynamicLocaleProvider
and is not annotating that function?

**Comment by JackPapa0156** [comment]
You are f*cking right - I must have lost my head today.
Great package, btw. Have a nice day! :)
