### ISSUE TITLE
Angularjs 1.7.x $cookieStore removed

### ISSUE THREAD

**Issue by f-aubert** [lgalfaso/angular-dynamic-locale#121]
Hello, maybe I'm wrong but service $cookieStore seems to have been removed. Is there any chance it to be replaced with service $cookies (see https://docs.angularjs.org/guide/migration#migrating-from-1-6-to-1-7) as I presently cannot upgrade to angular 1.7.x long term support and use angular-dynamic-locale.

**Comment by lgalfaso** [comment]
Hi, as a quick fix, you should be able to do

```js
angular.module(..., ['tmh.dynamicLocale', ...])
  .config(function(tmhDynamicLocaleProvider) {
    tmhDynamicLocaleProvider.useStorage('$cookies');
  })
```

I should be able to have a permanent fix within a few days.

**Comment by lgalfaso** [comment]
Version `0.1.36` should work as expected with Angular 1.7+.

Please let me know if you find any issues.

**Comment by f-aubert** [comment]
As far as I tested so far, it works great! It compiles and it runs. Thanks a lot for such a quick fix! You're amazing.
