### ISSUE TITLE
Strange $injector error on module load

### ISSUE THREAD

**Issue by psaia** [lgalfaso/angular-dynamic-locale#28]
```
var myApp = angular.module("myApp", ['tmh.dynamicLocale']);
```

As soon as the module is included into my app's module this error gets thrown:

```
Uncaught Error: [$injector:unpr] Unknown provider: $rootScopeProvider <- $rootScope <- tmhDynamicLocale
```

Libraries:  
- Angular 1.2.16
- angular-dynamic-locale 0.1.9

_edit_

I removed the `.run(['tmhDynamicLocale', angular.noop]);` from the module and now it seems to be working.

**Comment by diaconesq** [comment]
I just ran into this issue too. Turns out it was user error.

When injecting, I used:

    localeReader.$inject = ['tmh.DynamicLocale'];

instead of 
    localeReader.$inject = ['tmhDynamicLocale'];

(There is an extra dot in the 1st version).

It's a bit confusing, because the name of the module is 'tmh.DynamicLocale' (with a dot), but the name of the exposed service is 'tmhDynamicLocale'
