### ISSUE TITLE
can you given an example of using tmhDynamicLocaleProvider in angularjs

### ISSUE THREAD

**Issue by ericq** [lgalfaso/angular-dynamic-locale#50]
I'm a newbie in AngularJs.  can you provide an example how to add the following to initialize the tmhDynamicLocale. 

function(tmhDynamicLocaleProvider) {
      tmhDynamicLocaleProvider.localeLocationPattern('/base/node_modules/angular-i18n/angular-locale_{{locale}}.js');
    })

**Comment by diaconesq** [comment]
Could you please add the example to the description page of the project? I was lucky to stumble upon this page from Google. Others may not be so lucky.

**Comment by Sayvai** [comment]
@diaconesq I've just made a pull request with the change to README file showing example usage. I stumbled upon the solution here myself as well, luckily. Hopefully the owner @lgalfaso approves of this.

**Comment by tom94zoe** [comment]
This won't work if the directory was minified. Is there a solution without exlcude it from minification?

**Comment by lgalfaso** [comment]
@tom94zoe can you please elaborate a little more? If the locale files are not present anywhere to be read online, then you have the option to pre-load them into the cache as in #93

**Comment by tom94zoe** [comment]
Thank you, the referenced issue is pretty much that what I searched.
