### ISSUE TITLE
create a banner to put the version number inside the source code

### ISSUE THREAD

**Issue by afonso-praca** [lgalfaso/angular-dynamic-locale#53]
I think is easier to control the version of your lib when we have the version number inside the code. ie: just like angular does.

/*
 AngularJS v1.3.11
 (c) 2010-2014 Google, Inc. http://angularjs.org
 License: MIT
*/

Thanks in advance

**Comment by lgalfaso** [comment]
This is very reasonable, just landed a fix for this at 3a25cd8a5517f13daaff30a744ed27fe5d422944

**Comment by afonso-praca** [comment]
Thanks a lot. I am waiting for a new release with this feature. Maybe 0.1.25. Your module is very useful for me.
