### ISSUE TITLE
reference a Node in a context where it does not exist

### ISSUE THREAD

**Issue by ali-bugdayci** [lgalfaso/angular-dynamic-locale#55]
Getting errors on karma tests on both chrome and phantomjs

Version: ├── angular-dynamic-locale#0.1.27

```
PhantomJS 1.9.8 (Linux) ERROR
  NOT_FOUND_ERR: DOM Exception 8: An attempt was made to reference a Node in a context where it does not exist.
  at /home/bor/sunucu/mdm-server/public/lib/angular-dynamic-locale/tmhDynamicLocale.min.js:7
```

**Comment by lgalfaso** [comment]
Hi, thanks for reporting this.
- Are you using require.js?
- Would it be possible to have a plunker that shows this error?

Thanks

**Comment by ali-bugdayci** [comment]
Hi,

thanks for response. I might have prematurely created the issue. It might be broken becuase of phantomjs or something else.

Will let you know if I find anything
