### ISSUE TITLE
Minification fails

### ISSUE THREAD

**Issue by epeschier** [lgalfaso/angular-dynamic-locale#56]
Did you try minifying the js file? I'm getting this error: 
Unknown provider: nProvider <- n <- $exceptionHandler <- $rootScope <- tmhDynamicLocale

**Comment by lgalfaso** [comment]
There is a minified version at
https://github.com/lgalfaso/angular-dynamic-locale/blob/master/tmhDynamicLocale.min.js
,
but if you create a plunker with the error, I can try to figure out what is
wrong

**Comment by lgalfaso** [comment]
Another option is to start your app with strict-di enabled, and you will be
able to see what is the exact dependency that is wrong

**Comment by lgalfaso** [comment]
Without some extra information, it is not possible to know what is wrong. I am closing this as there is not enough information to diagnose the issue. In the case that there is a way to reproduce the issue, feel free to reopen it
