### ISSUE TITLE
Accessing locale varaibles

### ISSUE THREAD

**Issue by felixmau** [lgalfaso/angular-dynamic-locale#59]
Hello,

I'd like to know, if there is a way to access the locale variables after they've been loaded?

Greetings

**Comment by lgalfaso** [comment]
Hi,
  There are two ways, `tmhDynamicLocale.set(...)` returns a promise with the updated `$locale` or you can just look at `$locale` itself once the new locale is loaded.

**Comment by lgalfaso** [comment]
With no updates in the last 3 weeks, I think that the comment made it.
