### ISSUE TITLE
Locale didn't change dynamically for UI Bootstrap Datepicker

### ISSUE THREAD

**Issue by DieterLi** [lgalfaso/angular-dynamic-locale#60]
Actually, UI Bootstrap Date Picker can change the locale according to AngularJS I18N, by including different local js file in the head of the page.

But it doesn't take effect by this dynamic one, although the corresponding locale js file has been included into the web page indeed.

Do I need to do more actions to make it happen? There is no explanation in the introduction. Please help. Thanks in advance.

**Comment by lgalfaso** [comment]
UI Bootstrap Date Picker uses its own mechanism for formatting dates independent of `$locale`. What you have to do is hook into the promise that is returned when changing the locale and propagating this change to the configuration you set to Bootstrap UI.

Quite some time ago, I wrote http://plnkr.co/edit/x9IrQoaFiKTHHX6XrRig?p=preview that would be a possible way to make Bootstrap UI date picker work with dynamic locales. I have no idea if this still works with the current Bootstrap UI implementation, but it does not work with the version you are working on, it should be very little work to make that happen.

**Comment by lgalfaso** [comment]
Tested with the latest version of Bootstrap UI and the same plunker still works. The original plunker was for Bootstrap UI 0.10 and all the way to 0.13, seam to work. This is, if you use any of these versions, you should be good

**Comment by lgalfaso** [comment]
Just to keep it here in case someone else is having this issue, I am adding the relevant code here

```js
  // The module 'app' can be your main module or a module you depend on.
  angular.module('app', [])
  .config(function ($provide) {
    $provide.decorator('datepickerDirective', function($delegate) {
      angular.forEach($delegate, function (directive) {
        var originalCompile = directive.compile; 
        var originalLink = directive.link; 
        console.log($delegate);
        if (originalCompile) {
          directive.compile = function () {
            return function (scope) {
              scope.$on('$localeChangeSuccess', function () {
                scope.move(0);
              });
              originalLink.apply(this, arguments);
            };
          }
        }
      });
      return $delegate;
    });  
  });
```

**Comment by DieterLi** [comment]
Igalfaso, you've done a great job for the datepicker directive, which works great for me. Thanks a lot.

But unfortunately, my problem is using datepicker popup, and I'm not so familiar with source code about ui.bootstrap. I've tried several ways and failed. Any idea about it? Thanks in advance.

**Comment by lgalfaso** [comment]
@DieterLi there is no extra code needed to make it work with datepicker popup
http://plnkr.co/edit/SriQrUbqzbDzfIaeyeO8?p=preview

This is turning into support of a library that is not this, so I think there is nothing else to be handled in this issue and then I am closing it

**Comment by DieterLi** [comment]
@lgalfaso It's highly appreciated for what you've done. 

And I think I figured out that problem is caused by the version of ui.bootstrap. Since 0.11.0 and above, that mechanism has changed in ui.bootstrap. 

It also works fine on my side with ui.bootstrap 0.10.0. And currently, we are using 0.13.0, meanwhile the solution doesn't work any more. I wish I could fix it for ui.bootstrap 0.13.0, but limited on my AngularJS experiences.

It would be quite helpful, if there were any solution on after 0.10.0 versions. Thanks a lot.

**Comment by DieterLi** [comment]
@lgalfaso By the way, I really like your idea and the solution here. Quite brilliant.

**Comment by DieterLi** [comment]
@lgalfaso In 0.11.0 and above, datepicker directive still uses the same mechanism, and works fine. But for popup one, it's changed to a new way. So I guess it would need a new way to deal with it.

If there is not type for input tag, type="date", there isn't a popup, which doesn't like in 0.10.0

**Comment by DieterLi** [comment]
@lgalfaso I have to admit that is my fault. At first, I got confused about ui.bootstrap datepicker popup with Chrome supported HTML5 date input, which also provides a popup datepicker. 

Actually, this project works very well with the dynamic locale switching. 

Thanks a lot for your quick response and help.

**Comment by lgalfaso** [comment]
@DieterLi BTW, AFAIK, no browser allows any form of customization on the browser native implementation of date picker.

**Comment by DieterLi** [comment]
@lgalfaso Yes, you're quite right. It's my fault not differentiating the native calendar popup with the one provided by ui.bootstrap. 

The locale in native one depends on the language setting of operating system, as least on my Mac system and Chrome on it. So I don't bother to customise it. 

But as to ui.bootstrap datepicker popup, it works very well as you suggested. Thanks a lot, and I really like your idea here. Great job.

**Comment by moneytree-doug** [comment]
:+1: This is exactly what I needed.

**Comment by Badabum** [comment]
@lgalfaso , how to save selected date when change locale of datepicker? When I use your decorator everytime when I change locale selected value lost. Thanks.

**Comment by lgalfaso** [comment]
@Badabum would it be possible for you to create a plunker that shows this issue?

**Comment by joarhem** [comment]
Great work lgalfaso and great that you are so motivated in solving users problems :)

One remark, as I just stmbled over a little thing:
As Angular UI Bootstrap now names its directives with a "uib-" in front of the former Name (<uib-datepicker> instead of <datepicker>) in the code of lgalfaso the word 'datepickerDirective' must be replaced with 'uibDatepickerDirective'.

Then it also works with the newly named directives.

**Comment by Badabum** [comment]
@lgalfaso , Hi. I found that in angular ui-bootstrap lib version 0.13.4 function ```scope.move(direction)``` sets activeDate property to the first day of month. So, instead of using ```scope.move(0)``` I`ve used ``ctrls[1].refreshView()``` this works exactly the same way as ```scope.move()``` but doesnt set ```activeDate``` to first day of month. Maybe it'll be helpfull for someone.

**Comment by vincentcialdella** [comment]
Is this working with angularJS 1.4.x ?

**Comment by Badabum** [comment]
@vincentcialdella, at the moment I work with angular 1.4.4 and its working

**Comment by vincentcialdella** [comment]
This example is not working for me, I never log anything

`angular
	.module('myApp', [
		'ui.bootstrap'
	])
	.config(function($provide) {
		$provide.decorator('uibDatepickerDirective', function($delegate) {
			console.log('never logs this');
			var directive = $delegate[0];
			
			return $delegate;
		});
	});`

**Comment by Badabum** [comment]
@vincentcialdella , what version of [Angular UI](https://angular-ui.github.io/bootstrap/) do you use?

**Comment by vincentcialdella** [comment]
I'm using 1.0.3 version of angular-bootstrap
