### ISSUE TITLE
Handling when a file is not found or setting default locale file

### ISSUE THREAD

**Issue by ericjames** [lgalfaso/angular-dynamic-locale#63]
Can you give an example of how to handle when a file is not found?  Because I want to set a default locale file in case the language is not found.

**Comment by lgalfaso** [comment]
Are you talking about how to handle the case that the default locale is not set or the case that a normal locale is not set? For the default locale, it might be somehow difficult (but not impossible).
For all the other changes, it is a lot easier and there are two alternatives:
* listen for the event `'$localeChangeError'`
* `tmhDynamicLocale.set(...)` returns a promise, that promise is rejected if loading the locale fails.

**Comment by ericjames** [comment]
Oops I was actually asking for `tmhDynamicLocaleProvider.defaultLocale()` can you add this to your documentation.   I am using locale with pascalprecht's translate, so I'm looking for a lot of equivalent methods.

FYI the bit of code I was asking for was: 
```
      scope.$on('$localeChangeError', function () {
          doSomething();
      })
```
