### ISSUE TITLE
tmhDynamicLocaleProvider.defaultLocale() 

### ISSUE THREAD

**Issue by michaelgrossklos** [lgalfaso/angular-dynamic-locale#64]
If tmhDynamicLocaleProvider.defaultLocale() ist set it isn't possible to change the locale with thmDynamicLocale.set(). Is there any work around?

**Comment by lgalfaso** [comment]
`tmhDynamicLocaleProvider.defaultLocale()` sets the default locale upon initialization and the locale can be changed after without any issue. Would it be possible for you to create a plunker with the error you are seeing?

**Comment by michaelgrossklos** [comment]
There is no error message at all. It just don't work. If I console out `tmhDynamicLocaleProvider.getLocale()` after I call `set()` I only get the default, but not the new one. My solution is not to use `defaultLocale()`, but set the default language with `set()` in my main controller. That works too.

**Comment by lgalfaso** [comment]
Would it be possible for you to create a plunker that shows this error?

**Comment by Kroid** [comment]
@michaelgrossklos, maybe you use
```
tmhDynamicLocaleProvider.useStorage('$cookieStore')
```
?

**Comment by lgalfaso** [comment]
I have no way to reproduce this error. Closing. Feel free to reopen with more information on how to reproduce the error or with a plunker that shows the issue
