### ISSUE TITLE
Language Doesn't Change When Using $filter

### ISSUE THREAD

**Issue by rnicholls** [lgalfaso/angular-dynamic-locale#66]
When using $filter('currency')('100000', '$'); in a controller, the language doesn't change to the desired "Set" language.

**Comment by lgalfaso** [comment]
Would it be possible to get some more information? What is not working? Would it be possible for you to create a plunker that shows the error?

**Comment by rnicholls** [comment]
Hey, 

basically I am trying to have this work inside a directive because I need to manipulate the "translated" currency and ad some dom objects to it. But it always gives me english.

**Comment by lgalfaso** [comment]
You have to keep in mind 2 things:
* The locale chance asynchronously
* `$filter('currency')('100000', '$')` is a string, the string will not change when the locale chances

With this in mind, there are several things you can do, one of the simplest is to do `$scope.$watch(function() { return $filter('currency')('100000', '$'); }, function(value) { /* do something with value */ });`

**Comment by rnicholls** [comment]
That works. Thank you so much !

**Comment by lgalfaso** [comment]
Good that it helped!
