### ISSUE TITLE
Path/URL troubles with ui-router

### ISSUE THREAD

**Issue by lolmaus** [lgalfaso/angular-dynamic-locale#67]
We're using [ui-router](https://github.com/angular-ui/ui-router).

When accessing the app via a non-root page, e. g. `http://foo.bar/baz` instead of just `http://foo.bar/`, angular-dynamic-locale tries to load the locale file from `http://foo.bar/baz/angular/...` which obviously results in a 404.

Is there a way to resolve this issue?

**Comment by lolmaus** [comment]
Is there a way to customize the path?

**Comment by lgalfaso** [comment]
`tmhDynamicLocaleProvider.localeLocationPattern('http://baz.com/angular/i18n/angular-locale_{{locale}}.js')` should do it

**Comment by lgalfaso** [comment]
Or just `tmhDynamicLocaleProvider.localeLocationPattern('/angular/i18n/angular-locale_{{locale}}.js')`

**Comment by lolmaus** [comment]
Thank you, kind sir!
