### ISSUE TITLE
Angular2 Support?

### ISSUE THREAD

**Issue by LMFinney** [lgalfaso/angular-dynamic-locale#73]
Do you have any plans to add Angular2 support?

**Comment by lgalfaso** [comment]
> Do you have any plans to add Angular2 support?
>

Angular 2 is still under development, but once there is a clear path to do
on-demand code loading (and if this is not provided by the framework
itself). Then I plan on writing an angular 2 version of this library.

**Comment by LMFinney** [comment]
Thanks. I suspected as much. I'm working in Angular2 now, and it's too fluid to rely on it yet.

I was hoping, though :)
