### ISSUE TITLE
Is it possible to use ngstorage instead of $cookieStorage?

### ISSUE THREAD

**Issue by azachar** [lgalfaso/angular-dynamic-locale#75]

**Comment by lgalfaso** [comment]
never used ngStorage, but if it exposes a service that follows the same signature as `$cookieStorage` then `tmhDynamicLocaleProvider.useStorage('someOtherService')` will make it. If it does not follow the same signature, then it should be possible to create an intermediate service that does the right thing

**Comment by lgalfaso** [comment]
Without any answer, I expect that https://github.com/lgalfaso/angular-dynamic-locale/issues/75#issuecomment-138622093 provides the right solution
