### ISSUE TITLE
is it possible to have a table for the "localeLocationPattern" variable?

### ISSUE THREAD

**Issue by toofff** [lgalfaso/angular-dynamic-locale#78]
The goal would be to have several sources of dynamically import i18n file.

for exemple :
```
'use strict';
angular.module('MyApp').config([
  '$translateProvider', 'tmhDynamicLocaleProvider', function($translateProvider, tmhDynamicLocaleProvider) {
    $translateProvider.useStaticFilesLoader({
      prefix: 'i18n/json/locale-',
      suffix: '.json'
    });
    $translateProvider.preferredLanguage('fr');
    $translateProvider.useLocalStorage();
    $translateProvider.useSanitizeValueStrategy('escape');
    tmhDynamicLocaleProvider.defaultLocale('fr');
    return tmhDynamicLocaleProvider.localeLocationPattern([
      'i18n/angular-i18n/angular-locale_{{locale}}.js'
      'i18n/moment/{{locale}}.js'
    ]);
  }
])
```

**Comment by lgalfaso** [comment]
@toofff this looks interesting, but I am not sure what the specific behavior should be. Is the idea that each location is checked in sequence and accept the first locale that is successfully loaded?

**Comment by toofff** [comment]
The goal is to load all local that I have in my possession. For the moment the plugin can load a file type, for my project I want to load local files from several plugins at the same time.

Is what I am quite clear in my explanations?

**Comment by lgalfaso** [comment]
Sorry, but it is not clear the porpoise, would it be possible for you to
write a complete example?

**Comment by toofff** [comment]
Hello,

I use this as dependency :
- https://docs.angularjs.org/guide/i18n
- http://momentjs.com/

To import the translation files dynamically on my project, I use your dependency.

With several dependency, I have several translation files to be imported dynamically.

Currently I can dynamically import one file type but I would like to have  the opportunity to import more files dynamically. See my first example.

**Comment by lgalfaso** [comment]
@aaronhuckabee if you need an absolute URL, you should be able to do
```js
// Check that there is a "/' at the begging of the path
tmhDynamicLocaleProvider.localeLocationPattern('/angular/i18n/angular-locale_{{locale}}.js');
```

**Comment by lgalfaso** [comment]
This is now possible by using `tmhDynamicLocaleProvider.addLocalePatternValue`
