### ISSUE TITLE
move .min.js and .min.js.map to dist

### ISSUE THREAD

**Issue by maruilian11** [lgalfaso/angular-dynamic-locale#81]
could you please move `tmhDynamicLocale.min.js` and `tmhDynamicLocale.min.js.map` to dist so that we can add your lib on https://cdnjs.com with **git auto-update** and **npm auto-update**.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/6183

**Comment by lgalfaso** [comment]
Added the minified versions to dist with 64bba56d945c3d3269d55debef79aaffa5c0d513

**Comment by maruilian11** [comment]
:+1:

**Comment by alexissusset** [comment]
+1
