### ISSUE TITLE
Locales need a page refresh to be updated

### ISSUE THREAD

**Issue by xavierva** [lgalfaso/angular-dynamic-locale#83]
Hi,

I saw on the sample page that when we change locales data are updated.

But locales in my project need a page refresh to be updated.

Is there any option I'm missing ?

**Comment by lgalfaso** [comment]
Hi, if you can post a minimal plunker that shows the issue, then I can take
a look

**Comment by xavierva** [comment]
okay, my fault it was a stupid mistake in my code, I forgot to update the locale ...

So it works perfectly, thanks a lot !
