### ISSUE TITLE
Allow append the script element to a custom tag

### ISSUE THREAD

**Issue by miguelCT** [lgalfaso/angular-dynamic-locale#85]
Hello,

I've been playing around with the plugin and I've found I would need to customize the element tag in which the script element is appended. Currently the script element is appended to the body, but I think it would be a nice addition to be able to select a custom tag.

### Why the need?

In the project I'm working we use the ui-router plugin, so all the content is loaded from a ui view in the body tag 
```html
<body ui-view></body>
```
The problem is that your plugin appends the script element to body, but when the ui-router loads the application content it removes all the content inside the body tag (including the appended script tag).

The solution would be to add an optional configuration attribute (same as the localeLocationPattern) that would allow to specify the custom tag. In my case the head tag, for example:

```js
.config(['tmhDynamicLocaleProvider', function(tmhDynamicLocaleProvider){
	tmhDynamicLocaleProvider.appendScriptTo('head');
}]);
```

I've made the necessary changes in local, and I think ìt's a small non-invasive addition, but very useful when you want to append the script element to a different tag.

If you approve the proposal I can open a PR with the changes.

Thanks, in advance.

**Comment by lgalfaso** [comment]
This looks somehow of an edge case, but reasonable. The only thing I would do different is for `appendScriptTo` to take a DOM node. This is, in your example you would need to do `tmhDynamicLocaleProvider.appendScriptTo(document.head);`.

If this is ok, then please open a PR

**Comment by mariopolo2805** [comment]
+1

**Comment by lgalfaso** [comment]
Sorry for taking this long. Will merge and cut a new release this WE

**Comment by miguelCT** [comment]
Ah, no problem, Thank you for considering the feature.

**Comment by lgalfaso** [comment]
Sorry that it took this long, but this is now part of 0.1.30
