### ISSUE TITLE
angular-dynamic-locale works incorrect on android

### ISSUE THREAD

**Issue by zhaoxiong** [lgalfaso/angular-dynamic-locale#87]
angular-dynamic-locale works fine on browser,but does not work well on android(I use ionic to develop a hybrid mobile app).the tmhDynamicLocale.set('zh-CN') return a promise that enters error function.my mobile language setting is chinese

**Comment by lgalfaso** [comment]
Hi @zhaoxiong, would it be possible to get some extra context about this bug? What is causing the issue?

**Comment by zhaoxiong** [comment]
http://stackoverflow.com/questions/34897400/angular-dynamic-locale-works-incorrect-on-android

**Comment by zhaoxiong** [comment]
It works fine if I run it within anywhere(a tool like tomcat)

**Comment by lgalfaso** [comment]
Did http://stackoverflow.com/a/35633232/1924520 solved this issue? If this is not the case, feel free to reopen this issue.
