### ISSUE TITLE
Wrong distribution code versions

### ISSUE THREAD

**Issue by enrico-padovani** [lgalfaso/angular-dynamic-locale#88]
Hi,

when downloading from npm in the dist folder it appears that tmhDynamicLocale.js is 0.1.27 and tmhDynamicLocale.min.js is 0.1.30.

In this repo (release 0.1.30) the dist folder contains tmhDynamicLocale.js 0.1.27 and tmhDynamicLocale.min.js 0.1.29.

Could you please check and align the dist code version to the latest?

Thanks you so much,
Enrico

**Comment by lgalfaso** [comment]
Thanks for reporting this. Updated the versions at `dist` and updated the release script so the latest version is always there
