### ISSUE TITLE
Date filters not applied at run time when locale is changed

### ISSUE THREAD

**Issue by vincentcialdella** [lgalfaso/angular-dynamic-locale#96]
Hi,

When I change the locale, the dates are not formated according to the new locale: they don't change.
If I go back and come on the page, the format according to the new locale will be applied.

Any idea ?

**Comment by lgalfaso** [comment]
Are you using angular built-in date formatters? What angular version? Can
you create a plunker?

**Comment by vincentcialdella** [comment]
Actually it seems to come from angular-formly. When I use built-in date formatters directly in a view like this it's working
`<div>{{vm.formlyModel.fromDate | date:'shortDate'}}</div>`

However it's when I'm using datepicker template of angular-formly that it's not working.

**Comment by lgalfaso** [comment]
Hi, if you put together a plunker, then I can take a look

**Comment by lgalfaso** [comment]
closing this issue as there is no feedback
