### ISSUE TITLE
Blocked loading mixed active content

### ISSUE THREAD

**Issue by Crashillo** [lgalfaso/angular-dynamic-locale#99]
Hi,

I have a multi-language site, where you can change default language (`navigator.language`) from a selector, to modify angular locale files. Those files are in bower_components, so I had to override default path:
```
secure.config(function (tmhDynamicLocaleProvider) {
    tmhDynamicLocaleProvider.localeLocationPattern('bower_components/angular-i18n/angular-locale_{{locale}}.js');
});
```
No problem on localhost because it's over HTTP, but at the server is running over HTTPS, so I get the following message:
`Blocked loading mixed active content "http://**servername**/secure-integration/static/bower_components/angular-i18n/angular-locale_en.js`

How can tmhDynamicLocaleProvider serve that files over HTTPS? Is that possible?

**Comment by lgalfaso** [comment]
The browser is using the default protocol/server for the page. This is (in
most cases) the one that shows up in the url bar. If this is http, then the
protocol will be http and same for https.

**Comment by lgalfaso** [comment]
Without any activity, I assume that this is solved. If this is not the case, feel free to reopen this issue
